### ISSUE TITLE
[BUG] Cantar Truco rompe el programa

### ISSUE THREAD

**Issue by rovifran** [rovifran/aninfo2C23#56]
## 🐛 Bug Report

Cuando se canta truco, en cualquier mano, rompe el juego despues de hacer otro click.
Al hacer el primer click el juego no reacciona, despues del segundo click rompe

### Steps to Reproduce

1. Iniciar una Partida
2. Cantar Truco
3. Dar otro click

#### Stack trace & error message

```
Canto truco
Falta Envido
Traceback (most recent call last):
  File "/home/francisco/Desktop/AnInfo/src/truco.py", line 394, in <module>
    main()
  File "/home/francisco/Desktop/AnInfo/src/truco.py", line 341, in main
    partida.envido_actual.aceptar_envido()
AttributeError: 'NoneType' object has no attribute 'aceptar_envido'
```

Al parecer se llama a Falta Envido sin querer en algun lado

### Expected Behavior

Se tendria que dar un manejo parecido al envido, pero si se decide por `No Quiero` se deberia terminar la mano y sumar los puntos
### Your Environment

Me paso en Linux pero deberia pasar en cualquier SO

**Comment by rovifran** [comment]
Al parecer todavia no esta conectado jaja xd
